title: WoutBlog
author: Wouter Bijnsdorp
email: wouterb98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The best blog in the history of all blogs

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
